### ISSUE TITLE
Method "Model" does not exist?

### ISSUE THREAD

**Issue by MaxVoronov** [go-ozzo/ozzo-dbx#11]
Hi team.

I want try to use models like in your example:
```go
// SELECT * FROM customer WHERE id=100
db.Select().Model(100, &customer)
```
 But I don't see this method (screenshot attached). 
<img width="828" alt="DB Model?" src="https://cloud.githubusercontent.com/assets/8292606/17211007/5b9474ee-54cf-11e6-9706-c49a8756297e.png">
Please advise where my mistake? Thank you

**Comment by qiangxue** [comment]
Are you using the latest code?

**Comment by MaxVoronov** [comment]
Sorry, my bad. Thank you
