### ISSUE TITLE
Bug with timestamp fields

### ISSUE THREAD

**Issue by MaxVoronov** [go-ozzo/ozzo-dbx#13]
Hi team,
I find another bug: when I try to select _created_at_ field (timestamp without timezone, Postgres) then I receive empty value. For example:
```go
type User struct {
	Uid      int64
	Email    string
	CreatedAt time.Time
}

func main() {
	dbCon, _ := dbx.Open("postgres", fmt.Sprintf("host=%s user=%s password=%s dbname=%s sslmode=%s",
		"localhost", "postgres", "mysecretpassword", "demo", "disable"))
	dbCon.LogFunc = log.Printf

	var user User
	dbCon.Select().From("users").Where(dbx.HashExp{"uid": 1}).One(&user)
	log.Printf("User: %s", user)
}
```
Result:
```
2016/07/28 15:00:31 [7.10ms] Query SQL: SELECT * FROM "users" WHERE "uid"=1
2016/07/28 15:00:31 User: {%!s(int64=1) my@email.com 0001-01-01 00:00:00 +0000 UTC}
```
But in database exists correct data:
<img width="978" alt="2016-07-28 14 57 29" src="https://cloud.githubusercontent.com/assets/8292606/17213138/b2e9ac6c-54db-11e6-96e1-a960fe198460.png">
Please check this bug. Thank you

**Comment by qiangxue** [comment]
should be fixed now. Thanks for reporting!

**Comment by MaxVoronov** [comment]
Thank you)
