### ISSUE TITLE
Return "photo" table name instead "photos"?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#14]
```
Is it correct?

type Photo struct{
	Id int `json:"id"`
	Image string `json:"image"`
}

func (p *Photo) TableName() string {
	return "photos"
}

func (p *Photo) GetPhotos(id int) {
	var photos []Photo
	q := db.Select("id", "image").
		Where(dbx.HashExp{"actor_id":  id}).OrderBy("id")
	err := q.All(&photos)
	if err != nil {
		println("Exec err:", err.Error())
	}
	return
}
```

**Comment by kolkov** [comment]
```
Exec err: Error 1146: Table 'inframe.photo' doesn't exist
2016-07-28T22:03:45+03:00 [Info][app] [3.00ms] Query SQL: SELECT `id`, `image` FROM `photo` WHERE `actor_id`=1 ORDER BY `id`
```

**Comment by MaxVoronov** [comment]
Hi Andrey,
I think you right. This is bug. I tested and when we use slice (for example `var photos []Photo`) then did not fire method `TableName()`. But for `var photo Photo` all works fine.

**Comment by kolkov** [comment]
I tried to debug it, but my debugger does not receive some variables ... (((
https://github.com/go-lang-plugin-org/go-lang-idea-plugin/issues/2693

**Comment by qiangxue** [comment]
Define `TableName()` with a value receiver instead of a pointer receiver. Otherwise, a `Photo` instance is not considered implementing the TableModel interface.

**Comment by kolkov** [comment]
Like this?
´´´
func (p Photo) TableName() string {
    return "photos"
}
´´´

**Comment by kolkov** [comment]
I think you need to update the readme:
1. This issue
2. About using "Join"

Thanks!

**Comment by qiangxue** [comment]
Sure. Here you are: https://github.com/go-ozzo/ozzo-dbx/commit/2aca3b6d69214e29c48f745efe1792f2df66d189

**Comment by kolkov** [comment]
In the README nothing about JOIN yet ((

> Building Query Conditions:
> When building a query condition expression, its parameter values will be populated using parameter binding, which prevents SQL injection from happening. Also if an expression involves column names, they will be properly quoted. The following condition building functions are available:
> 
> dbx.NewExp(): creating a condition using the given expression string and binding parameters. For example, dbx.NewExp("id={:id}", dbx.Params{"id":100}) would create the expression id=100.
> dbx.HashExp: a map type that represents name-value pairs concatenated by AND operators. For example, dbx.HashExp{"id":100, "status":1} would create id=100 AND status=1.
> dbx.Not(): creating a NOT expression by prepending NOT to the given expression.
> dbx.And(): creating an AND expression by concatenating the given expressions with the AND operators.
> dbx.Or(): creating an OR expression by concatenating the given expressions with the OR operators.
> dbx.In(): creating an IN expression for the specified column and the range of values. For example, dbx.In("age", 30, 40, 50) would create the expression age IN (30, 40, 50). Note that if the value range is empty, it will generate an expression representing a false value.
> dbx.NotIn(): creating an NOT IN expression. This is very similar to dbx.In().
> dbx.Like(): creating a LIKE expression for the specified column and the range of values. For example, dbx.Like("title", "golang", "framework") would create the expression title LIKE "%golang%" AND title LIKE "%framework%". You can further customize a LIKE expression by calling Escape() and/or Match() functions of the resulting expression. Note that if the value range is empty, it will generate an empty expression.
> dbx.NotLike(): creating a NOT LIKE expression. This is very similar to dbx.Like().
> dbx.OrLike(): creating a LIKE expression but concatenating different LIKE sub-expressions using OR instead of AND.
> dbx.OrNotLike(): creating a NOT LIKE expression and concatenating different NOT LIKE sub-expressions using OR instead of AND.
> dbx.Exists(): creating an EXISTS expression by prepending EXISTS to the given expression.
> dbx.NotExists(): creating a NOT EXISTS expression by prepending NOT EXISTS to the given expression.
> dbx.Between(): creating a BETWEEN expression. For example, dbx.Between("age", 30, 40) would create the expression age BETWEEN 30 AND 40.
> dbx.NotBetween(): creating a NOT BETWEEN expression. For example
