### ISSUE TITLE
How can I get Where expression from q?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#16]
I want to use alternative method for pagination, because this slower on tests.

http://stackoverflow.com/questions/4765901/mysql-sql-calc-found-rows-and-pagination
http://www.xarg.org/2011/10/optimized-pagination-using-mysql/

**Comment by qiangxue** [comment]
If you have the where expression `e`, you can use `e.Build(db, params)` to get the SQL fragment (if that's you are looking for).
