### ISSUE TITLE
Query.Column(): populate the first column of the result into a slice. Error

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#21]
q.Column undefined (type *dbx.SelectQuery has no field or method Column)
this works only for commented statement.
```Go
func (m *User)GetEmailsAll() []string {
	q := db.Select("email") //q := db.NewQuery("SELECT `email` FROM `users`")
	var emails []string
	q.Column(&emails)
	return emails
}
```

**Comment by qiangxue** [comment]
Fixed in https://github.com/go-ozzo/ozzo-dbx/commit/8eaf82754a91bf51dc20052205e602479214a9d7
Thanks!
