### ISSUE TITLE
Error when scan mysql timestamp into time.Time

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#22]
SELECT * FROM `actor` LIMIT 5

Exec err: sql: Scan error on column index 8: unsupported Scan, storing driver.Value type []uint8 into type *time.Time

```
type Actor struct{
	Id int
	deleted bool
	CreateDate string
	UpdatedAt time.Time
	Person
}
```

**Comment by kolkov** [comment]
`Exec err: sql: Scan error on column index 8: converting driver.Value type []uint8 ("2016-08-08 02:49:40") to a int64: invalid syntax`

**Comment by qiangxue** [comment]
What's the column type are you using? From the error, it seems it's because the column type is not supported to be parsed as time.Time. Note that ozzo-dbx doesn't do the parsing. It's the underly DB driver does the conversion.

**Comment by kolkov** [comment]
```
actor

Столбец	Тип	Null	По умолчанию	Комментарии
id	int(11)	Нет 	 	 
deleted	set('no', 'yes')	Нет 	no 	 
last_name	varchar(50)	Нет 	 	 
first_name	varchar(50)	Нет 	 	 
patronymic	varchar(50)	Нет 	 	 
birthday	date	Нет 	 	 
avatar_url	varchar(100)	Нет 	/img/face.png 	 
create_date	timestamp	Нет 	 	 
updated_at	timestamp	Нет 	CURRENT_TIMESTAMP 	 
gender	set('male', 'female')	Нет 	 	 
edu	smallint(6)	Нет 	 	 
Индексы

Имя индекса	Тип	Уникальный	Упакован	Столбец	Уникальных элементов	Сравнение	Null	Комментарий
PRIMARY	BTREE	Да	Нет	id	18	A	Нет	

```

**Comment by kolkov** [comment]
Thanks!
`?parseTime=true` worked for me with MySQL

**Comment by qiangxue** [comment]
yeah, that's needed in order for the driver to properly handle time.Time.

**Comment by denilbhatt0814** [comment]
> Thanks! `?parseTime=true` worked for me with MySQL

Thanks it worked for me too
