### ISSUE TITLE
How can store complex entity into database with ozzo properly?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#23]
If I populate Actor with `Actor` and `Person` attributes, how can I store (INSERT, UPDATE) it into db tables `actor` and `person` with the same structure?
```Go
type Actor struct{
	Id         int64
	deleted    bool
	ParsonId   int64
	Alias      string
	CreateDate string
	UpdatedAt  time.Time
	Person
}

type Person struct {
	Id 	       int64
	LastName   string
	FirstName  string
	Patronymic string
	Birthday   string
	Gender     string
	AvatarUrl  string
}
```

**Comment by kolkov** [comment]
...or I can create:
```Go
type Actor struct{
    Id         int64
    deleted    bool
    ParsonId   int64
    Alias      string
    CreateDate string
    UpdatedAt  time.Time
    Person Person
}
```

**Comment by qiangxue** [comment]
This is not supported as ozzo-dbx is not an ORM and does not support relational mapping.
You would need to manually call Insert/Update for each model.

**Comment by kolkov** [comment]
Thanks!

**Comment by kolkov** [comment]
How to populate objects properly in this case (struct has the same field names and I need only Actor CreatedAt and UpdatedAt fields)? Or it's a wrong way at all?
and this expression ``LeftJoin("person", dbx.NewExp("`person`.`id` = `actor`.`person_id`")).`` is correct?
```Go
type Actor struct{	
	Id int
	deleted bool
	PersonId int
	Alias string
	CreatedAt time.Time
	UpdatedAt time.Time
        Person
}

type Person struct {
	Id 	   int
	UserId 	   int
	LastName   string
	FirstName  string
	Patronymic string
	Birthday   string
	Gender     string
	AvatarUrl  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (m *Actor) GetAll(from, limit int64) []Actor {
	var actors []Actor
	q := db.Select().
		LeftJoin("person", dbx.NewExp("`person`.`id` = `actor`.`person_id`")).
		Limit(limit).
		Offset(from)

	err := q.All(&actors)
	if err != nil {
		println("Exec err:", err.Error())
	}	
	return actors
}
```

**Comment by qiangxue** [comment]
If `Person` is in the last, its `Id` field will be masked by `Actor.Id` when being populated, unless you alias the selected column as `person.id`.

In general, dbx is not an ORM. Each model should usually be associated with a single table. If you want to handle the relational case like your example, I would avoid JOIN and use two single-table SELECTs.

**Comment by kolkov** [comment]
Did you mean: ``SELECT FROM `actor` LIMIT``, then ``SELECT from `person` WHERE actor.person_id = person.id`` each row in cycle?

**Comment by qiangxue** [comment]
Yes. The second query should also filter according to the selected actor IDs from the first query result.

**Comment by kolkov** [comment]
Whether it will be much slower?

**Comment by kolkov** [comment]
Is this correct in my case? 
You say:
> If Person is in the last, its Id field will be masked by Actor.Id when being populated, unless you alias the selected column as person.id.

Query SQL: ``SELECT `actor`.`id`, `alias`, `actor`.`created_at`, `actor`.`updated_at`, `last_name`, `first_name`, `patronymic` FROM `actor` LEFT JOIN `person` ON `person`.`id` = `actor`.`person_id` LIMIT 5``

![image](https://cloud.githubusercontent.com/assets/3740898/17555693/29622184-5f19-11e6-8b28-88a9822ad55e.png)

![image](https://cloud.githubusercontent.com/assets/3740898/17555713/407489d4-5f19-11e6-9353-0845a75bb9f2.png)

![image](https://cloud.githubusercontent.com/assets/3740898/17555732/518a1c7a-5f19-11e6-9136-b7c46684d542.png)

![image](https://cloud.githubusercontent.com/assets/3740898/17555762/71edec94-5f19-11e6-95f4-62a6627cc2bc.png)

**Comment by kolkov** [comment]
And AvatarUrl populated as expected...

![image](https://cloud.githubusercontent.com/assets/3740898/17556544/73f40be2-5f1c-11e6-834c-1a18095b1dd3.png)


![image](https://cloud.githubusercontent.com/assets/3740898/17556414/009e9432-5f1c-11e6-9e6b-f06f9a148254.png)

![image](https://cloud.githubusercontent.com/assets/3740898/17556440/12bebec6-5f1c-11e6-8bde-16115ac8a8b2.png)

![image](https://cloud.githubusercontent.com/assets/3740898/17556456/24063bd2-5f1c-11e6-896e-c2c6b74108d5.png)

`SELECT `actor`.`id`, `alias`, `actor`.`created_at`, `actor`.`updated_at`, `last_name`, `first_name`, `patronymic`, `actor`.`avatar_url` FROM `actor` LEFT JOIN `person` ON `person`.`id` = `actor`.`person_id` LIMIT 5`

**Comment by qiangxue** [comment]
There are two ways. 

1. Embed `Person` as an anonymous field in `Actor` (as you are already doing). For `Person.Id` field, define a struct tag to associate it with a db column named `person_id`.

1. Embed `Person` in `Actor` as a non-anonymous field `type Actor struct {Person Person, ...}`. And then `SELECT person.id AS "person.id"...`

**Comment by kolkov** [comment]
Yes it worked partly (1 way), but what about if I want to SELECT data from Person with separate query? And what about CreatedAt and UpdatedAt fields?

**Comment by kolkov** [comment]
Not good, but it usable... 
```go
type Actor struct{
	Id int
	deleted bool
	PersonId int
	Alias string
	/*AvatarUrl string
	CreatedAt time.Time
	UpdatedAt time.Time*/
	Person
}
```
![image](https://cloud.githubusercontent.com/assets/3740898/17558729/3bc92100-5f24-11e6-85a4-cdd5fbe584be.png)

It would be nice to come up with some interesting solution ...)

**Comment by qiangxue** [comment]
If you are using the first approach, you may also tag the anonymous Person field as `person` and then do `SELECT person.id AS "person.id"...`

**Comment by kolkov** [comment]
Ok, I will try this now.

One question more...
```go
type User struct {
	Id        int
	UserName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (u *User) BeforeInsert(){
	u.CreatedAt = time.Now()
	u.UpdatedAt= u.CreatedAt
}

func (u *User) BeforeUpdate(){
	u.UpdatedAt = time.Now()
}

func (u *User) Create() error{
	u.BeforeInsert()
	err:= db.Model(u).Insert()
	if err != nil{
		println("Exec err:", err.Error())
	}
	return err
}
```
Why time is not quoted?

``INSERT INTO `user` (`created_at`, `updated_at`, `user_name`) VALUES (2016-08-10 18:09:31.1670022 +0300 MSK, 2016-08-10 18:09:31.1670022 +0300 MSK, '')``

**Comment by kolkov** [comment]
> If you are using the first approach, you may also tag the anonymous Person field as person and then do SELECT person.id AS "person.id"...
Yes! This is the best solution now.

**Comment by qiangxue** [comment]
The SQL you see is only for logging purpose. It is not the actual SQL being executed.
I will add a fix for this.

**Comment by kolkov** [comment]
> The SQL you see is only for logging purpose. It is not the actual SQL being executed.
> I will add a fix for this.

Ok! But I has a error when try inserting by my app...
Thanks a lot!

**Comment by qiangxue** [comment]
what error?

**Comment by kolkov** [comment]
While not fully understand ... (
```
2016/08/10 18:31:37 http: TLS handshake error from 127.0.0.1:2356: EOF
[mysql] 2016/08/10 18:37:16 packets.go:124: write tcp 127.0.0.1:2359->127.0.0.1:3306: wsasend: An established connection was aborted by the software in your host machine.
[mysql] 2016/08/10 18:37:16 packets.go:124: write tcp 127.0.0.1:2359->127.0.0.1:3306: wsasend: An established connection was aborted by the software in your host machine.
2016-08-10T18:37:16+03:00 [Info][app] [3.00ms] Query SQL: SELECT `actor`.`id`, `alias`, `actor`.`created_at`, `actor`.`updated_at`, `last_name` AS `person.last_name`, `first_name` AS `person.first_name`, `patronymic` AS `person.patronymic`, `actor`.`avatar_url`, `person`.`id` AS `person.id`, `birthday` AS `person.birthday`, `gender` AS `person.gender` FROM `actor` LEFT JOIN `person` ON `person`.`id` = `actor`.`person_id` LIMIT 0
2016-08-10T18:37:16+03:00 [Info][app] [0.00ms] Query SQL: SELECT count(*) FROM `actor`
2016-08-10T18:37:16+03:00 [Info][app.webserver] [127.0.0.1] [3.002ms] GET /api/v1/actor/pagination HTTP/2.0 200 25
2016-08-10T18:37:17+03:00 [Info][app.webserver] [127.0.0.1] [0.501ms] GET /app/private/base/actor/new.html HTTP/2.0 200 4039
2016-08-10T18:37:42+03:00 [Info][app] [4.00ms] Execute SQL: INSERT INTO `user` (`created_at`, `updated_at`, `user_name`) VALUES (2016-08-10 18:37:42.6526322 +0300 MSK, 2016-08-10 18:37:42.6526322 +0300 MSK, '')
Exec err: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`inframe`.`person`, CONSTRAINT `person_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE CASCADE)
2016-08-10T18:37:42+03:00 [Info][app] [1.50ms] Execute SQL: INSERT INTO `person` (`avatar_url`, `birthday`, `created_at`, `first_name`, `gender`, `id`, `last_name`, `patronymic`, `updated_at`, `user_id`) VALUES ('', '', 2016-08-10 18:37:42.6526322 +0300 MSK, '', '', 9, '', '', 2016-08-10 18:37:42.6526322 +0300 MSK, 0)
Exec err: Error 1054: Unknown column 'person.avatar_url' in 'field list'
2016-08-10T18:37:42+03:00 [Info][app] [0.00ms] Execute SQL: INSERT INTO `actor` (`alias`, `person`.`avatar_url`, `person`.`birthday`, `person`.`created_at`, `person`.`first_name`, `person`.`gender`, `person`.`last_name`, `person`.`patronymic`, `person`.`updated_at`, `person`.`user_id`, `person_id`) VALUES ('', '', '2012-12-31T21:00:00.000Z', 0001-01-01 00:00:00 +0000 UTC, 'test', 'male', 'test', 'test', 0001-01-01 00:00:00 +0000 UTC, 0, 9)
2016-08-10T18:37:42+03:00 [Info][app.webserver] Error 1054: Unknown column 'person.avatar_url' in 'field list'
```

**Comment by qiangxue** [comment]
Seems there are a few errors. Please try to isolate them first.

* SELECT `actor`.`id`, `alias`, `actor`.`created_at`, `actor`.`updated_at`, `last_name` AS `person.last_name`, `first_name` AS `person.first_name`, `patronymic` AS `person.patronymic`, `actor`.`avatar_url`, `person`.`id` AS `person.id`, `birthday` AS `person.birthday`, `gender` AS `person.gender` FROM `actor` LEFT JOIN `person` ON `person`.`id` = `actor`.`person_id` LIMIT 0: *why limit 0 here?*
* Exec err: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`inframe`.`person`, CONSTRAINT `person_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE CASCADE)
* Exec err: Error 1452: Cannot add or update a child row: a foreign key constraint fails (`inframe`.`person`, CONSTRAINT `person_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`) ON UPDATE CASCADE)

**Comment by kolkov** [comment]
Not very convenient, first I get an error from
```go
err := db.Model(m).Insert()
	if err != nil {
		fmt.Println("Exec err:", err.Error())
	}
```
Ang then from ozzo-log))

I found first! )
`person.id = user.id` )) changed to `person.UserId = user.Id`

**Comment by kolkov** [comment]
> why limit 0 here?

it's a bug in my Angular app. Thanks!

**Comment by kolkov** [comment]
Now there was one mistake `'person.avatar_url'` 
```
2016-08-10T19:33:53+03:00 [Info][app] [3.50ms] Execute SQL: INSERT INTO `user` (`created_at`, `updated_at`, `user_name`) VALUES (2016-08-10 19:33:53.5873129 +0300 MSK, 2016-08-10 19:33:53.5873129 +0300 MSK, '')
2016-08-10T19:33:53+03:00 [Info][app] [1.50ms] Execute SQL: INSERT INTO `person` (`avatar_url`, `birthday`, `created_at`, `first_name`, `gender`, `last_name`, `patronymic`, `updated_at`, `user_id`) VALUES ('', '', 2016-08-10 19:33:53.5873129 +0300 MSK, '', '', '', '', 2016-08-10 19:33:53.5873129 +0300 MSK, 13)
Exec err: Error 1054: Unknown column 'person.avatar_url' in 'field list'
2016-08-10T19:33:53+03:00 [Info][app] [0.50ms] Execute SQL: INSERT INTO `actor` (`alias`, `person`.`avatar_url`, `person`.`birthday`, `person`.`created_at`, `person`.`first_name`, `person`.`gender`, `person`.`last_name`, `person`.`patronymic`, `person`.`updated_at`, `person`.`user_id`, `person_id`) VALUES ('', '', '2016-08-03T21:00:00.000Z', 0001-01-01 00:00:00 +0000 UTC, 'test3', 'male', 'test3', 'test3', 0001-01-01 00:00:00 +0000 UTC, 0, 7)
2016-08-10T19:33:53+03:00 [Info][app.webserver] Error 1054: Unknown column 'person.avatar_url' in 'field list'
2016-08-10T19:33:53+03:00 [Info][app.webserver] [127.0.0.1] [6.504ms] POST /api/v1/actor/save HTTP/2.0 500 89
```

**Comment by kolkov** [comment]
And if I change to:
```go
type Actor struct{
	Id int
	deleted bool
	PersonId int
	Alias string
	AvatarUrl string
	CreatedAt time.Time
	UpdatedAt time.Time
	Person `db:"person"`
}

func (m *Actor) Create() error {
	m.beforeInsert()
	err := db.Model(m).Insert("person_id", "avatar_url", "alias", "created_at", "updated_at")
	if err != nil {
		fmt.Println("Exec err:", err.Error())
	}
	return err
}
```
Error is:
```
Exec err: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT VALUES' at line 1
2016-08-10T20:02:55+03:00 [Info][app] [1.00ms] Execute SQL: INSERT INTO `actor` DEFAULT VALUES
2016-08-10T20:02:55+03:00 [Info][app.webserver] Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT VALUES' at line 1
```

**Comment by qiangxue** [comment]
`db.Model(m).Insert(...)` should list the struct field names, not db column names.
The error shows you don't have a table column named avatar_url.

**Comment by kolkov** [comment]
Yes! But how can I prevent this?
```
2016-08-10T22:37:57+03:00 [Info][app] [2.50ms] Execute SQL: INSERT INTO `user` (`created_at`, `updated_at`, `user_name`) VALUES (2016-08-10 22:37:57.4409857 +0300 MSK, 2016-08-10 22:37:57.4409857 +0300 MSK, '')
2016-08-10T22:37:57+03:00 [Info][app] [1.00ms] Execute SQL: INSERT INTO `person` (`avatar_url`, `birthday`, `created_at`, `first_name`, `gender`, `last_name`, `patronymic`, `updated_at`, `user_id`) VALUES ('', '2016-08-09T21:00:00.000Z', 2016-08-10 22:37:57.4409857 +0300 MSK, 'test10', 'male', 'test10', 'test10', 2016-08-10 22:37:57.4409857 +0300 MSK, 22)
Exec err: Error 1054: Unknown column 'person.avatar_url' in 'field list'
2016-08-10T22:37:57+03:00 [Info][app] [0.00ms] Execute SQL: INSERT INTO `actor` (`alias`, `person`.`avatar_url`, `person`.`created_at`, `person`.`updated_at`, `person_id`) VALUES ('', '', 0001-01-01 00:00:00 +0000 UTC, 0001-01-01 00:00:00 +0000 UTC, 16)
2016-08-10T22:37:57+03:00 [Info][app.webserver] Error 1054: Unknown column 'person.avatar_url' in 'field list'
```
```go
type Actor struct{
	Id int
	deleted bool
	PersonId int
	Alias string
	AvatarUrl string
	CreatedAt time.Time
	UpdatedAt time.Time
	Person `db:"person"`
}

func (m *Actor) Create() error {
	/*tx, _ := db.Begin()*/
	m.beforeInsert()
	err := db.Model(m).Insert("PersonId", "AvatarUrl", "Alias", "CreatedAt", "UpdatedAt")
	if err != nil {
		fmt.Println("Exec err:", err.Error())
	}
	return err
}
```

**Comment by qiangxue** [comment]
Are you saying the line `    err := db.Model(m).Insert("PersonId", "AvatarUrl", "Alias", "CreatedAt", "UpdatedAt")`
executes the following SQL?

```
INSERT INTO `actor` (`alias`, `person`.`avatar_url`, `person`.`created_at`, `person`.`updated_at`, `person_id`) VALUES ('', '', 0001-01-01 00:00:00 +0000 UTC, 0001-01-01 00:00:00 +0000 UTC, 16)
```

**Comment by kolkov** [comment]
I want to save only Actor fields without Person lields...

**Comment by kolkov** [comment]
I tried this construction:
`err := db.Model(m).Exclude("Person").Insert()`
No changes...(

**Comment by kolkov** [comment]
I think we need to change logic of this function. Add only columns not present into exclude []string.
And then use like `db.Model(model).Select().Exclude("Person")`. Now first we create all columns and then remove excluded from map.
```go
// columns returns the struct field values indexed by their corresponding DB column names.
func (s *structValue) columns(include, exclude []string) map[string]interface{} {
	v := map[string]interface{}{}
	if len(include) == 0 {
		for _, fi := range s.nameMap {
			v[fi.dbName] = fi.getValue(s.value)
		}
	} else {
		for _, attr := range include {
			if fi, ok := s.nameMap[attr]; ok {
				v[fi.dbName] = fi.getValue(s.value)
			}
		}
	}
	if len(exclude) > 0 {
		for _, name := range exclude {
			if fi, ok := s.nameMap[name]; ok {
				delete(v, fi.dbName)
			}
		}
	}
	return v
}
```

**Comment by kolkov** [comment]
Sorry ( This is not possible at this place(
```
&{structInfo:0xc0423d8c90 value:{typ:0x8ef0e0 ptr:0xc042000400 flag:409} tableName:actor}
map[Birthday:0xc042237980 Gender:0xc0422379c0 Id:0xc042237840 Alias:0xc042237780 CreatedAt:0xc042237a40 UpdatedAt:0xc042237a80 LastName:0xc0422378c0 PersonId:0xc042237740 UserId:0xc042237880 FirstName:0xc042237900 Patronymic:0xc042237940 AvatarUrl:0xc042237a00]
```

**Comment by qiangxue** [comment]
I see the problem: when populating Actor, you want to populate Person as well by tagging it with a prefix "person."; when inserting Actor, you want to skip Person - but Person and Actor have some fields with the same name. I do not have a good solution for this problem now, but I will think about it.

**Comment by kolkov** [comment]
There is a blessing in disguise, as they say in Russia ("нет худа без добра")!
But now I know how ozzo-dbx works inside)))

**Comment by kolkov** [comment]
I think the best solution is to tag fields only for reading and only for writing separately.
At moment we have solution for change column name ``Person `db:"person"` `` and ``Person `db:"-"` `` for disable reading and writing.
It will be good idea to have solution like this: ``Person `db:"<"` `` field only for reading and ``Person `db:">"` `` field only for writing.
I don't know is it possible?
In my opinion it maybe possible at stage where we creating table structure:

```go
func getStructInfo(a reflect.Type, mapper FieldMapFunc) *structInfo {
	muStructInfoMap.Lock()
	defer muStructInfoMap.Unlock()

	key := structInfoMapKey{a, reflect.ValueOf(mapper)}
	if si, ok := structInfoMap[key]; ok {
		return si
	}

	si := &structInfo{
		nameMap:   map[string]*fieldInfo{},
		dbNameMap: map[string]*fieldInfo{},
	}
	si.build(a, make([]int, 0), "", "", mapper)
	structInfoMap[key] = si

	return si
}

func (si *structInfo) build(a reflect.Type, path []int, namePrefix, dbNamePrefix string, mapper FieldMapFunc) {
	n := a.NumField()
	for i := 0; i < n; i++ {
		field := a.Field(i)
		tag := field.Tag.Get(DbTag)

		// only handle anonymous or exported fields
		if !field.Anonymous && field.PkgPath != "" || tag == "-" {
			continue
		}

		path2 := make([]int, len(path), len(path)+1)
		copy(path2, path)
		path2 = append(path2, i)

		ft := field.Type
		if ft.Kind() == reflect.Ptr {
			ft = ft.Elem()
		}

		name := field.Name
		dbName, isPK := parseTag(tag)
		if dbName == "" && !field.Anonymous {
			if mapper != nil {
				dbName = mapper(field.Name)
			} else {
				dbName = field.Name
			}
		}
		if field.Anonymous {
			name = ""
		}

		if isNestedStruct(ft) {
			// dive into non-scanner struct
			si.build(ft, path2, concat(namePrefix, name), concat(dbNamePrefix, dbName), mapper)
		} else if dbName != "" {
			// non-anonymous scanner or struct field
			fi := &fieldInfo{
				name:   concat(namePrefix, name),
				dbName: concat(dbNamePrefix, dbName),
				path:   path2,
			}
			si.nameMap[fi.name] = fi
			si.dbNameMap[fi.dbName] = fi
			if isPK {
				si.pkNames = append(si.pkNames, fi.name)
			}
		}
	}
	if len(si.pkNames) == 0 {
		if _, ok := si.nameMap["ID"]; ok {
			si.pkNames = append(si.pkNames, "ID")
		} else if _, ok := si.nameMap["Id"]; ok {
			si.pkNames = append(si.pkNames, "Id")
		}
	}
}
```

**Comment by kolkov** [comment]
And then in the `q.model.columns(attrs, q.exclude)` we can scan fields structure for labels only "for reading" and "only for writing" and take only necessary columns. Is it possible?
```go
func (q *ModelQuery) Insert(attrs ...string) error {
	if q.lastError != nil {
		return q.lastError
	}
	cols := q.model.columns(attrs, q.exclude)
	pkName := ""
	for name, value := range q.model.pk() {
		if isAutoInc(value) {
			delete(cols, name)
			pkName = name
			break
		}
	}

	if pkName == "" {
		_, err := q.builder.Insert(q.model.tableName, Params(cols)).Execute()
		return err
	}

	// handle auto-incremental PK
	query := q.builder.Insert(q.model.tableName, Params(cols))
	pkValue, err := insertAndReturnPK(q.db, query, pkName)
	if err != nil {
		return err
	}
	indirect(q.model.dbNameMap[pkName].getField(q.model.value)).SetInt(pkValue)
	return nil
}
```

**Comment by kolkov** [comment]
Or may be through change functioning of exclude statment `data.Model(m).Exclude("Person").Insert()`

**Comment by qiangxue** [comment]
It's possible, but I'm afraid this introduces more complexity to the usage.
The real problem here is that you are trying to use the same struct for both reading and writing purposes. It can be solved in the following way:
```go
type Actor struct {...}  // do not embed Person here
type Person struct {...}
type ActorPerson struct {
    Actor
    Person  `db:"person"`
}
```

You use Actor and Person for writing purpose (or reading purpose if you do not need the relational data). And you use ActorPerson for reading purpose when you want to have the relational data ready.

**Comment by kolkov** [comment]
Thank you! Interesting idea)
