### ISSUE TITLE
Why Id populates from joined table?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#27]
Hi, Qiang! Happy New Year 2017!
I use this code to populate `FeedPersonName` struct from MySQL tables. But Feed.Id, Feed.CreatedAt etc. populates with Id, CreatedAt etc. from Person table not from Feed. Is it correct?

Feed
```
type Feed struct{
	Id int
	deleted bool
	PersonId int
	Heading string
	Body string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type FeedPersonName struct {
	Feed
	Person PersonName
}

func (m FeedPersonName) TableName() string {
	return "feed"
}
```
PersonName
```
type PersonName struct {
	LastName string `json:"last_name"`
	FirstName string `json:"first_name"`
}

func (m PersonName) TableName() string {
	return "person"
}
```
FeedDAO
```
func (dao *FeedDAO) Query(rs app.RequestScope, offset, limit int) ([]models.Feed, error) {
	feed := []models.Feed{}
	err := rs.Tx().Select().InnerJoin("person", dbx.NewExp("`feed`.`person_id` = `person`.`id`")).OrderBy("id").Offset(int64(offset)).OrderBy("feed.id DESC").Limit(int64(limit)).All(&feed)
	return feed, err
}
```

![image](https://cloud.githubusercontent.com/assets/3740898/21596755/a515faf4-d150-11e6-8434-15cef6e3e448.png)

![image](https://cloud.githubusercontent.com/assets/3740898/21596768/d6bd9990-d150-11e6-914c-0335fdeefa2e.png)

![image](https://cloud.githubusercontent.com/assets/3740898/21596779/fcc08a94-d150-11e6-9130-2c5a833e45b8.png)

**Comment by qiangxue** [comment]
There are two `Id` columns being returned. This is a bit special. The current implementation will take the second `Id` column. I suggest you avoid this situation by explicitly selecting one `Id` column that you really want.

**Comment by kolkov** [comment]
Yes, I did the same, but it seems to me that this is not quite right ...
Thanks!

**Comment by qiangxue** [comment]
What is not quite right?
