### ISSUE TITLE
dbx.In() when data arrives in slice.

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#28]
Hi!
How to use `dbx.In()` expression when data arrives in the slice like this:
`[]string{"read", "unread"}`

**Comment by qiangxue** [comment]
`dbx.In("column", values...)` ?

**Comment by kolkov** [comment]
And how to use this? Provide some examples please...

**Comment by kolkov** [comment]
Like this?
`statuses := []interface{}{"read", "unread"}`

`.Where(dbx.In("status", statuses...))`

right?

**Comment by qiangxue** [comment]
yes
