### ISSUE TITLE
How to use dbx in the models?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#3]
Hi!
What the best way to use dbx in the models?
DI? Context? 
Or way like this? 
http://idealogylabs.com/blog/golang/2015/07/11/golang-and-mvc.html

**Comment by qiangxue** [comment]
dbx is not an ORM. It's mainly a DB abstraction layer (like Yii's DAO layer). You can use it to build your own ORM or model layer. The examples showing in README should tell you how to use dbx to populate structs.

**Comment by kolkov** [comment]
Thanks! And how can I get db Instance in the model layer?

**Comment by qiangxue** [comment]
I usually create a globally accessible `App` object which contains configurations loaded from config files as well as other objects (such as db instance).

**Comment by kolkov** [comment]
I've heard that global objects are dangerous. 
And it is better to use this way:
https://elithrar.github.io/article/custom-handlers-avoiding-globals/

**Comment by qiangxue** [comment]
It all depends on how you use them. Ultimately the goal is to avoid scattering implicit dependencies on global variables everywhere. Like the article you referenced, you may pass along these variables through Context, thus avoiding directly referencing the global variables. However, in practice this could be painful to do, especially if you have many such variables.

**Comment by kolkov** [comment]
Can you give an example of a method proposed by you (with package structure)?
