### ISSUE TITLE
How to build query with FIND_IN_SET?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#35]
Like this:
`mysql> SELECT * FROM tbl_name WHERE FIND_IN_SET('value',set_col)>0;`

**Comment by qiangxue** [comment]
`.Where(dbx.NewExp("FIND_IN_SET('value',set_col)>0"))`
or simply write the whole SQL directly.
Note that the query builder is meant to simplify building common SQLs, not to complicate things.

**Comment by kolkov** [comment]
thanks!
