### ISSUE TITLE
SelectQuery.FieldMapper isn't set by NewSelectQuery

### ISSUE THREAD

**Issue by nkovacs** [go-ozzo/ozzo-dbx#36]
If you do this:

```
err := db.Select().Model(id, &model)
```

db's `FieldMapper` is not passed down to `SelectQuery`, so if the primary key has a different name in the database, it will fail.

**Comment by nkovacs** [comment]
I wrote a fix, but it breaks backwards compatibility because NewSelectQuery has changed: https://github.com/nkovacs/ozzo-dbx/commit/3867baf6ecc2dd0c2c071818d89300b9e6915935

**Comment by qiangxue** [comment]
Thank you for reporting this issue and finding a fix for it!
