### ISSUE TITLE
Why the field name must lower case?

### ISSUE THREAD

**Issue by ScottHuangZL** [go-ozzo/ozzo-dbx#4]
Below will work:
q := db.NewQuery("SELECT id, username as name FROM tbl_users order by id LIMIT 10 ")

**However, below not work:**
q := db.NewQuery("SELECT id, username as Name FROM tbl_users order by id LIMIT 10 ")

It seem ozzo-dbx only prefer the field name as lowercase.

Could you advise why we have to use lower case filed name?
How to lift this limitation? Thanks.

**Comment by qiangxue** [comment]
This is explained in README: https://github.com/go-ozzo/ozzo-dbx#executing-queries

You can use struct field tags to explicitly specify which column names to use. You can also specify `Query.FieldMapper` to use your own field mapper. The default one will do what you described.

**Comment by ScottHuangZL** [comment]
Thanks for the confirmation.
