### ISSUE TITLE
Select queries in transactions

### ISSUE THREAD

**Issue by nkovacs** [go-ozzo/ozzo-dbx#40]
I think [this commit](https://github.com/go-ozzo/ozzo-dbx/commit/0e21bcb0bc03006bf6b2cace9619f13740dbff93) broke select queries in transactions again (which was fixed here: https://github.com/go-ozzo/ozzo-dbx/commit/2dd287b3c2d5210d13a719767b81b092957142d0)

**Comment by qiangxue** [comment]
Thanks!
