### ISSUE TITLE
How to use NullStringMap?

### ISSUE THREAD

**Issue by susilolab** [go-ozzo/ozzo-dbx#41]
hi qiang, i write simple code to query data but its return error "panic: assignment to entry in nil map"
but when i change ```rows.ScanMap(row)``` to ```rows.ScanMap(&row)```, its return "cannot use &row (type *dbx.NullStringMap) as type dbx.NullStringMap in argument to rows.ScanMap"

this is my code:
```Go
sql := "SELECT id, username FROM swt_user LIMIT 1"

var row dbx.NullStringMap
q := db.NewQuery(sql)

rows, err := q.Rows()
if err != nil {
	log.Println(err)
}

for rows.Next() {
	rows.ScanMap(row)
	fmt.Println(row)
}
```

**Comment by qiangxue** [comment]
You need to initialize your map before passing it to `ScanMap`:

```go
row := dbx.NullStringMap{}
```

**Comment by susilolab** [comment]
thanks sir, it's perfectly work :)
