### ISSUE TITLE
How I can get LAST_INSERT_ID after insert?

### ISSUE THREAD

**Issue by rudyavsky-ag** [go-ozzo/ozzo-dbx#64]
I have found insertAndReturnPK(...), but Insert() not returned this value. I need to get last inserted PK in threadsafe mode. Any ideas?

**Comment by kolkov** [comment]
As I know last Insert_Id populated into the model after inserting...

**Comment by rudyavsky-ag** [comment]
Can You provide some examples of ussage? Another question: what should i do if another process (e.g. perl/python) exacute insert at same time?

**Comment by kolkov** [comment]
https://github.com/go-ozzo/ozzo-dbx/issues/20

If two applications simultaneously access the same database table, then this situation is solved by the SQL server.
