### ISSUE TITLE
How to set null in select with builder?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-dbx#79]
Such as `Select("null as railroad")`?
Thanks!

**Comment by kolkov** [comment]
I think we need to change this code:
https://github.com/go-ozzo/ozzo-dbx/blob/e984ee904f1b2df904d0b2e6b2ca5064c87c0409/db.go#L238:15
Add condition: if column name quoted by `'` do not quote this,it's not a column name!

**Comment by qiangxue** [comment]
Try `Select("(null) as railroad")`

**Comment by kolkov** [comment]
Thanks! This works!
