### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by Kalinin-Andrey** [go-ozzo/ozzo-dbx#83]
Are you planning to develop a migration mechanism?
What do you use for migrations yourself?

**Comment by qiangxue** [comment]
Nope, because there are already good solutions, e.g. golang-migrate.
Please check https://github.com/qiangxue/go-rest-api for an example of using migration.

**Comment by Kalinin-Andrey** [comment]
Thanks for the answer!
Yes, I know this package, but it only supports SQL. I would also like support for Go code.

**Comment by kolkov** [comment]
@qiangxue , please add in the documentation at the top the links to examples of using libraries on the Starter kit. I think many questions will disappear right away.
