### ISSUE TITLE
Many to many relation problem

### ISSUE THREAD

**Issue by zikwall** [go-ozzo/ozzo-dbx#89]
Hello!
I am trying to make a query with two joined tables like this:

```go
LeftJoin("content_tag ct", dbx.NewExp("content.id=ct.content_id")).
LeftJoin("tags", dbx.NewExp("ct.tag_id=tags.id"))
```
But in the answer I get emptiness...
The structure is as follows:

```go
type Content struct {
	Id         int64
	...
	Tags []tag.Tag
}
```

When joining another tag table, I still get the error: `panic: sql: Scan error on column index 13, name "id": converting NULL to int64 is unsupported` - it points to the column content.id int64.

Why are data from the database not saved to the structure?

**Comment by kolkov** [comment]
Hi! Try to get resulting sql query and check result by phpmyadmin for example.
I think you need to specify selected columns with table prefix in the `select()` method.

**Comment by zikwall** [comment]
I think I understand you, thank you very much.
