### ISSUE TITLE
表字段有一个为空的时候 q.All(&model) 全部为空

### ISSUE THREAD

**Issue by uiexp** [go-ozzo/ozzo-dbx#9]
表字段有一个为空的时候 q.All(&model) model全部为空

**Comment by uiexp** [comment]
补充 为 timestamp 字段的时候

**Comment by uiexp** [comment]
类型换 time.Time 正常。

**Comment by qiangxue** [comment]
Could you provide table schema and the code to reproduce the issue?

**Comment by uiexp** [comment]
CREATE TABLE `user` (
  `id` int(10) NOT NULL,
  `username` varchar(30) NOT NULL,
  `password` varchar(30) NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO `user` (`id`, `username`, `password`, `created_at`, `updated_at`) VALUES
(1, 'admin', '123456', '2016-05-20 08:18:31', '2016-05-19 16:00:00'),
(2, 'slenes', '123456', '2016-05-19 08:40:15', NULL);


ALTER TABLE `user`
  ADD UNIQUE KEY `id` (`id`),
  ADD UNIQUE KEY `username` (`username`);

ALTER TABLE `user`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;`


type User struct {
	Id       int
	Username string
	Password string
	Created  string	`db:"created_at"`
	Updated  string `db:"updated_at"`
}



api.Get("/users", func(c *routing.Context) error {
		var users []model.User
		q := db.Select("*").
		From("user").
		OrderBy("id")
		q.All(&users)
		return c.Write(users)
	})

结果：
[{"Id":1,"Username":"admin","Password":"123456","Created":"2016-05-20 16:18:31","Updated":"2016-05-20 00:00:00"}]  
Updated 为空的记录没有现实

**Comment by qiangxue** [comment]
你查看一下q.All()的返回值，应该是有错误的。错误的原因是string无法表达NULL，你需要用sql.NullString
