### ISSUE TITLE
Can't get last inserted id for pgx.

### ISSUE THREAD

**Issue by thangmo** [go-ozzo/ozzo-dbx#94]
@qiangxue
The program that I wrote use **pgx** driver (https://github.com/jackc/pgx) for PostgreSQL. I found the **dbx** can use **pgx** driver from here.
https://github.com/go-ozzo/ozzo-dbx/blob/c0868b7fa469684fd21331c4b0c334d732d039f9/db.go#L75-L82
When I try to insert a new record with the Insert() method like the document page. The code as below.
```
err := db.Model(&customer).Insert()
```
I encountered some error like ***"LastInsertId is not supported by this driver"***

I think the function insertAndReturnPK() should also check for **pgx** driver.
Both **pgx** and **postgres** driver use for PostgreSQL, but PostgreSQL doesn't support for LastInsertID().
https://github.com/go-ozzo/ozzo-dbx/blob/c0868b7fa469684fd21331c4b0c334d732d039f9/model_query.go#L107-L114

[sory for my poor English skill]

**Comment by qiangxue** [comment]
Thank you for reporting this issue! Could you verify the fix?

**Comment by dharmavagabond** [comment]
Yes, it works. :thumbsup:
